### ISSUE TITLE
Harvest tweaks crashing my world when mining asteroids 

### ISSUE THREAD

**Issue by cb12438** [NFINIT-Development/AstroBlock#113]
![Screen Shot 2020-09-05 at 12 02 18 PM](https://user-images.githubusercontent.com/55159369/92312073-44ee4e80-ef72-11ea-9a26-406fe7ab5cf8.png)
thats the screen shot i took when it crashed my world
[crash-2020-09-05_12.02.03-client.txt](https://github.com/NFINIT-Development/AstroBlock/files/5178519/crash-2020-09-05_12.02.03-client.txt)
thats the crash report it is prob something on my end but idk if its something with the pack plz fix

**Comment by knoxhack** [comment]
Fixed
