### ISSUE TITLE
Radiation level

### ISSUE THREAD

**Issue by JuliusLongmind** [NFINIT-Development/AstroBlock#114]
Hi,

It is a pleasure to see a new subversion of AstroBlock. Thanks a lot for your effort!

The radiation level isn't increasing or at least it is extremely slow.

Music stops and doesn't start anymore.

Br

**Comment by JuliusLongmind** [comment]
With 1.2.3 version music & radiation level fixed! Thanks a lot!

**Comment by knoxhack** [comment]
Awesome 😎
