### ISSUE TITLE
Asteroids spawning in Overworld

### ISSUE THREAD

**Issue by KongoLeo** [NFINIT-Development/AstroBlock#115]
When I finally got to the Overworld, I found asteroids like the ones in the Asteroids dimension. I checked them out with Spectator mode and it seems to only be Tin and Silver Ore asteroids. Additionally, none are appearing underground.

**Comment by KongoLeo** [comment]
Update: found a Copper Ore Asteroid as well.

**Comment by KongoLeo** [comment]
Update: As far as I can see, it is Lead, Silver, Tin, and Copper Ore asteroids, but I'd be willing to bet that Aluminum is out there as well. I have not seen any Gold, Iron or Coal Ore asteroids.

**Comment by knoxhack** [comment]
Ohh, I just pushed 1.2.3 fixing this. Thanks for reporting
