### ISSUE TITLE
Basic Wafer, oreDict issue with silicon

### ISSUE THREAD

**Issue by burshaz** [NFINIT-Development/AstroBlock#12]
Appears that the oreDict for silicon does not pass to the basic wafer.  The non GC silicon does work in the recipe.

ver 1.1.12

**Comment by knoxhack** [comment]
🤔

**Comment by burshaz** [comment]
Probably close this as I think the newer pack versions have corrected it.  At this point I don't remember how I got the non-GC silicon, maybe quest reward?  I have done multiple restarts to test early game and haven't encountered the situation again.
