### ISSUE TITLE
"Aluminum Ore" quest does not oreDict Silicon

### ISSUE THREAD

**Issue by burshaz** [NFINIT-Development/AstroBlock#14]
This quest does not see the non-GC silicon. 

Ver 1.1.12

**Comment by knoxhack** [comment]
Fixed in 1.1.13

**Comment by burshaz** [comment]
Started a fresh 1.1.26 world on a fresh install of the pack.  AE silicon does not have a recipe for the basic wafer via the circuit fabricator
