### ISSUE TITLE
Deep Mob learning & Evolved mobs

### ISSUE THREAD

**Issue by burshaz** [NFINIT-Development/AstroBlock#15]
In deep mob learning; It appears that the evolved(space version) of the mobs are not registered with the mod.  Should the be?

Ver 1.1.12

**Comment by burshaz** [comment]
Also the intro quest for Deep Mob Learning does not recognize the guide book.

There by preventing the chain while still in space.

**Comment by knoxhack** [comment]
This mod is meant to be used once getting to earth

**Comment by xt9** [comment]
Quick FYI. On later versions you can specify what mobs should count for the various models, so in the config you could put the registrynames of the evolved mobs in the corresponding models. Maybe you knew about this and wanted the player to only progress the models on earth but I thought I would let you know.

**Comment by knoxhack** [comment]
This was implemented already, evolved mobs now count too
