### ISSUE TITLE
Scannable & Silicon Ore

### ISSUE THREAD

**Issue by burshaz** [NFINIT-Development/AstroBlock#16]
Of the three types of silicon, the one with the tool tip "Can be found on Earth and inside asteroids" does not display in the scanner, either as a common or a rare ore.

This is the one i've found in the asteroids.  When block type scanning with the scanner, it displays "tile.basic_block_core.name".  This when scanned will also show "Solid Meteoric Iron," both in a blue highlight.  Setting a block type scanning to "Solid Meteoric Iron" will also show the silicon in the scanner.

Should silicon ore show with common or rare scanning?  Is the block scanning method the intended method, be it via either silicon or meteoric iron?

Ver 1.1.12

**Comment by knoxhack** [comment]
🤔

**Comment by knoxhack** [comment]
Fixed
