### ISSUE TITLE
Cow Hide and Leather conversions

### ISSUE THREAD

**Issue by burshaz** [NFINIT-Development/AstroBlock#17]
Cow hide which is early obtainable from the rotten flesh compression recipe has many uses.  But it can be converted in a 1to1 fashion into leather(minestrapolation 5) with no processing with just the crafting table.  Leather in this form has limited uses.

Maybe there should be a reversing recipe from leather back into cowhide to prevent player from accidentally ending up with the limited use version(leather)

**Comment by burshaz** [comment]
Ver 1.1.12

**Comment by knoxhack** [comment]
Fixed in 1.1.13
