### ISSUE TITLE
Intro quest for Deep Mob Learning does not recognize the guide book.

### ISSUE THREAD

**Issue by metalim** [NFINIT-Development/AstroBlock#19]
The intro quest for Deep Mob Learning does not recognize the guide book. Deep Mob Learning chain is therefore locked.

_Originally posted by @burshaz in https://github.com/NFINIT-Development/AstroBlock/issues/15#issuecomment-454193209_

**Comment by knoxhack** [comment]
Fixed in 1.1.13
