### ISSUE TITLE
Rocketry chapter quest issues

### ISSUE THREAD

**Issue by Deiwos** [NFINIT-Development/AstroBlock#23]
After obtaining a Tier 2 Rocket schematic, I turned in the quest below the 'go to the moon' quest (which now says Visit Dimension: Nether along with all of the other visit planet quests since the 1.1.13 update) and said quest consumed the schematic (why?) and gave me the research papers but didn't get marked as complete as, I suspect, it's set to be repeatable (why, again?). This means the 'build a tier 2 rocket' quest doesn't open up, as the schematic quest is marked as a prerequisite.

https://i.imgur.com/aavbjHy.png

**Comment by knoxhack** [comment]
Fixed
