### ISSUE TITLE
Electric Furnace Quest completed by Energy Storage Module

### ISSUE THREAD

**Issue by xanderhunter** [NFINIT-Development/AstroBlock#24]
Created a Energy Storage Module from Galacticraft Core and it completed the 2nd quest in the Mekanism Tab that asks you to make a Electric Furnace.

**Comment by xanderhunter** [comment]
I believe it also completed Circuit Fabricator when I crafted another one, didn't actually see it complete this time.

**Comment by knoxhack** [comment]
Fixed
