### ISSUE TITLE
Free Sieve Boost

### ISSUE THREAD

**Issue by ghost** [NFINIT-Development/AstroBlock#26]
Pack Version 1.1.19

Right clicking food onto the Auto Heavy Sieve gives a boost and consumes the food. However if you right click with canned food (Galacticraft Canned Dehydrated Apples) it gives the boost but does not consume the food. Free sieve boost :)

**Comment by knoxhack** [comment]
I kinda don't mind it 😅

**Comment by ghost** [comment]
Haha, sounds good to me.
