### ISSUE TITLE
Worldgen Mars Dungeon Chest

### ISSUE THREAD

**Issue by blacksythe** [NFINIT-Development/AstroBlock#28]
One of the players on my private server advised he found no chest in one of the mars dungeons.

I imagine this is more galacticraft mod related but I am posting it here in case a fix is found.

![image](https://user-images.githubusercontent.com/11398873/52731921-d5db8e80-2fb6-11e9-893f-9a73c919c1e3.png)

**Comment by knoxhack** [comment]
Invalid

**Comment by knoxhack** [comment]
Not able to replicate
