### ISSUE TITLE
Quest bug

### ISSUE THREAD

**Issue by Zebrix** [NFINIT-Development/AstroBlock#29]
Pickup Liquifacted coal bucket complete _Naphtha bucket_ and _Fuel bucket_ quests.

**Comment by Werewolf74** [comment]
Another quest bug, i craft the iron backpack after the first one backpack complete, but the iron backpack does not complete the next quest of the line, some thing is wrong, i test it on single and on your multiserver, by all bouth the same result.

regards

Spowsi

**Comment by Werewolf74** [comment]
Another quest bug, i craft the Enrichment Chamber nd the quest by Mekanism line does not complete the task.

Edit: the same with Crusher from Mekanism idk have all the first machine in this line this bug without the metallurgic infuser? Oo

Ok there is a lot of mekanism task can not complete the quest. can you pls fix that?

regards

Spowsi

**Comment by burshaz** [comment]
Related issue? There are two "ftbquests" folders in the config folder.

A "ftbquests" and a "ftbquests2" they appear to have identical data within.  

Maybe not an issue?  I did a fresh install to verify ver. 1.1.21

**Comment by knoxhack** [comment]
Yeah, already fixed

**Comment by Keetarin** [comment]
Another quest seems to be bugging out, specifically the magma crucible is not detecting and as such the quest cannot be completed, at least not on my world.
