### ISSUE TITLE
Crashed World

### ISSUE THREAD

**Issue by ghost** [NFINIT-Development/AstroBlock#31]
Left the overworld in a Tier 3 rocket and the planet selection screen would not load. I let it show the rocket animation for about 5 minutes. Reloaded the world and the selection screen now appears and the world then crashed. Crash log attached. 

[crash-2019-02-16_20.34.27-client.txt](https://github.com/NFINIT-Development/AstroBlock/files/2872579/crash-2019-02-16_20.34.27-client.txt)

**Comment by knoxhack** [comment]
As a temp fix try:
"I had this issue. I was getting a render error. Try resizing the window while loading and exiting the galaxy screen"

**Comment by ghost** [comment]
That worked, thanks! Got the world back. I wonder if that would help the rocket trip, there is a tick to it and it seems to take a while to get to the galaxy screen, even though the indicator is off the screen
