### ISSUE TITLE
1.1.20 Redstone Furnace stopped smelting

### ISSUE THREAD

**Issue by DDzwiedziu** [NFINIT-Development/AstroBlock#32]
Tried with fish and compressed sawdust. Nothing related found in the logs.

Edit: The receipies are present, otherwise wouldn't bother bug filling.
Edit 2: Remembered that this probably happened around a bug where the Redstone Furnace could smelt regular Charcoal. I've started doing a small power setup with this, but before I've finished (or after I've upgraded from .19 or I've restarted the game) the setup it started producing Infected Charcoal. I've left the setup, maybe upgraded it to handle Pyrolytic Conversion and then it stopped smelting anything. But after that a basic Redstone Furnace stopped smelting also. Will try restarting the game first.

**Comment by knoxhack** [comment]
Not able to replicate
