### ISSUE TITLE
1.1.20 Resource Fisher – Won the Game

### ISSUE THREAD

**Issue by DDzwiedziu** [NFINIT-Development/AstroBlock#33]
IMO it breaks the early game. Very cheap and provides a lot of fish (perfect for the Ocelot Pet and generating ~~RF~~ FE), leather, enchanted items (mending galore), water bottles for radiation potions (with the additional bonus that rad potions made from those bottles don't produce an empty bottle to litter the inventory), etc.

**Comment by knoxhack** [comment]
I don't really see a problem with that maybe I'll tweak the recipe
