### ISSUE TITLE
Moon schematics drop when breaking walls in NASA workbench rooms in asteroid dungeons

### ISSUE THREAD

**Issue by Celethang** [NFINIT-Development/AstroBlock#35]
I'm not sure if this is a secret or a bug. I found it out when I was tearing down the dungeons for the free building materials.

Specifically in NASA workbench rooms, when you break some of the walls behind them, you get tier 2 rocket and moon buggy schematics. I'm guessing they're supposed to be hanging on the walls, but they don't render or even show up in One Probe when you aim at the walls (in case they were invisible or something).

Judging by the questbook, I'm guessing you're supposed to find those two schematics on the Moon, so I'm wondering if it's a bit of sequence breaking being able to get them right away in the Asteroids.

**Comment by knoxhack** [comment]
Yeah, it doesn't really break progression since you need to go to the moon first to be able to unlock the research required for tier 2 planets
