### ISSUE TITLE
Digital Miner/ Nibiru Crash

### ISSUE THREAD

**Issue by ghost** [NFINIT-Development/AstroBlock#37]
Putting the digital miner on Nibiru and having it mine ore* crashed the world with a ticking entity. Pack version 1.1.21
[crash-2019-02-25_20.19.36-server.txt](https://github.com/NFINIT-Development/AstroBlock/files/2903342/crash-2019-02-25_20.19.36-server.txt)

**Comment by knoxhack** [comment]
https://github.com/SteveKunG/MorePlanets/issues/56

**Comment by knoxhack** [comment]
Fixed in dev, fix will be included in next update

**Comment by knoxhack** [comment]
Implemented in 1.1.27
