### ISSUE TITLE
Item Duplication

### ISSUE THREAD

**Issue by ghost** [NFINIT-Development/AstroBlock#39]
#38 - Related?

In the dark energy generator interface, if you have a stack of ingots in your hotbar and try to shift-click them into the generator, it fills your inventory with duplicated ingots. Also, works in reverse -  shift-clicking from your inventory, fills empty hotbar spaces. 

Does not work with 1 ingot, but 2 becomes 3, 3 becomes 6, 6 becomes 21, etc. Seems to work with most stackable items.

**Comment by James103** [comment]
The exact sequence here (2,3,6,21,231,...) is [OEIS A007501](http://oeis.org/A007501), in case anyone's wondering what causes the dark energy item duplication.﻿
