### ISSUE TITLE
Tritanium Crates possibly bugged

### ISSUE THREAD

**Issue by Phewsion** [NFINIT-Development/AstroBlock#42]
Hi
After the 1.1.24 update the Tritanium Crates that I had recieved from quest rewards no longer have any items in them, have rotated 90 degrees and aren't breakable with Fluxbore, Diamond Pickaxe or Desh Pickaxe, I tried restoring a backup save but didn't work.

Here is a screenshot of me holding the Desh Pickaxe over 1 of the crates
![2019-03-06_15 31 48](https://user-images.githubusercontent.com/37968676/53851977-3cd3ec80-4025-11e9-966f-f83df47891e6.png)

Edit: After 1.1.25 update, still can't break the crates, and have lost 90% of my items I was using those crates for all the ores and the satellites/dungeons I had cleared out :(

**Comment by Knoxxar** [comment]
here too, all items in the crates are gone. updatet to version 1.1.25
i hope my players on the server had not so much stuff in there ....

**Comment by Phewsion** [comment]
I was using them to store Galaticraft items
Have tested it by starting a new game, starter chest is in normal position with items inside, but can't be broken by any pickaxe.

**Comment by Knoxxar** [comment]
i had checked the other crates from my players on the server, all items are gone and the crates stand all like in the picture from Phewsion. How can i fix this?, for players where started yesterday, they will spam me with this error.

**Comment by knoxhack** [comment]
Apparently the Matter Overdrive update did that, you can rollback a backup before the 1.1.24 update and go back to 1.1.23

**Comment by knoxhack** [comment]
I'll push a fix on 1.1.26 so other player don't get this

**Comment by Knoxxar** [comment]
ok thx for the info

**Comment by knoxhack** [comment]
rolled back matter overdrive in 1.1.26

**Comment by Phewsion** [comment]
TY for the update, I did the rollback, then update to 1.1.26 then restored a backup from pre 1.1.42 and all my items cameback, much appreciated for the quick fix :D
