### ISSUE TITLE
AE2 Facades missing

### ISSUE THREAD

**Issue by gisikw** [NFINIT-Development/AstroBlock#43]
AE2 facades are uncraftable, possibly by design? Config seems to show that glass and quartz glass facades should be explicitly whitelisted, however neither are craftable. Would like to avoid leaving gaps in walls with routed cable.

Workaround for the moment would be to use AE2 energy cells as "pass-through" entities, I suppose.

If facades are meant to be entirely disabled though, probably best to remove cable anchor recipe entirely, no?

**Comment by knoxhack** [comment]
Correct, they were disabled by design. 
I don't like JEI spammed with Facades.

I'll look into removing Cable Anchor if necessary.

Thank you for the initiative to give feedback on this.

**Comment by gisikw** [comment]
@knoxhack That makes sense - though it does make the terminals and cables rather frustrating. 

JEI edit mode should auto-append items to the blacklist (config/jei/itemBlacklist.cfg). Would it be feasible to keep the recipes but simply remove them from JEI, rather than removing them entirely? That would keep the flexibility but avoid the clutter.

**Comment by knoxhack** [comment]
Not familiar with that, interesting. 
Will look into it

**Comment by gisikw** [comment]
Cheers - here's an example of what you'd want if you're comfortable going down this route: https://gfycat.com/watchfulsmallgrayreefshark
