### ISSUE TITLE
[REQUEST] Oredict ores and ingots

### ISSUE THREAD

**Issue by BonaireDreams** [NFINIT-Development/AstroBlock#45]
Astroblock 1.1.26
Galcticraft ingots are not oredict'd with Thermal Ingots. 
Pulverized Asteroid Aluminum ore in a TE pulverizor, cooked it in a TE furnace. Unable to use it in Galacticraft recipes.

**Comment by Heregerifa** [comment]
there is an upgrade that can be used on storage drawers (uses lapis) that will allow them to convert if you have one of the original type.
