### ISSUE TITLE
1.1.27 patch breaks the pack progression

### ISSUE THREAD

**Issue by alecium** [NFINIT-Development/AstroBlock#47]
In the 1.1.27 update, the quest to receive the Jupiter research paper requires the Tier 5 Rocket Schematic, which is found, according to the quest tooltip, in tier 5 chests on Jupiter... which you can't get to without discovering Jupiter via the research paper.  The same issue happens for all the other higher tier schematics/research paper quests.  This basically breaks the planetary progression in the pack, hindering the ability of finding the ores and such to progress in all other aspects of the pack.

**Comment by alecium** [comment]
basically, the quest that should give you the jupiter research paper instead gives you a mars paper.  The quest that should give you the saturn paper, instead gives you jupiter, etc.  Essentially the quests give you the proper "moons" research papers, but all the "planet" research papers are off by 1 quest.

**Comment by knoxhack** [comment]
Fixed in 1.1.28
