### ISSUE TITLE
Wood chippings unattainable

### ISSUE THREAD

**Issue by Based199** [NFINIT-Development/AstroBlock#49]
After latest update, using a stone hammer on oak wood gives you Thermal Expansion sawdust, not wood chippings, which in turn prevents you from making plastic.

Also tried using sawdust in the recipe to make plastic, and that didn't work.

**Comment by knoxhack** [comment]
Oh, I need to fix that

**Comment by knoxhack** [comment]
Thanks for reporting it

**Comment by Based199** [comment]
Update: So i'm just really dumb and i now realize that sawdust and wood chippings are ore dictionaried, and when holding a forge lexicon, it will automatically turn wood chippings into sawdust, giving the appearance that its bugged when its actually not. Easy fix for it auto turning chippings into sawdust is to search up wood chippings in the forge lexicon and select it as the preferred item.
