### ISSUE TITLE
Mekanism factories not recognised by questbook 

### ISSUE THREAD

**Issue by Heregerifa** [NFINIT-Development/AstroBlock#50]
Made the Mekanism mchines which were recognised, but the basic factories highlighted as next step are not.  Am I missing some other step or is this a glitch?  I know there were several previous oddities with the quests.

**Comment by BonaireDreams** [comment]
I noticed this with a few quests. One player on our server built the Basic Factory before the quest was unlocked. He then picked up after doing the previous quest. Was not recognised. He then built a new one from scratch. Same challenge. I then cheated one in for him and it was recognised.

I had the same issue with the backpacks questline. Crafted the basic backpack, quest completed. Used that backpack to craft the iron version. Quest did not complete. I had to cheat an identical one in for it to recognise. Same thing happened when I upgraded to Gold backpack. The crafted one did not work, the one I cheated in did.
