### ISSUE TITLE
Android Data Model [Deep Mob Learning] Doesn't Produce Right Loot

### ISSUE THREAD

**Issue by MrBrix123** [NFINIT-Development/AstroBlock#52]
It produces zombie pristines instead of android pristines.

**Comment by WhyThisJorgal** [comment]
As far as I know there is no android pristines so it generates zombie ones

**Comment by dorn284** [comment]
There are indeed Pristine Rogue Android Matters in game. It seems the data model is just flat out wrong for the Android in general. Killing them doesn't charge the card, zombies do. When you use the card in the simulator, it spawns zombie Pristines. 

Not sure if there's a way to fix it client side yet, I'm still searching.

**Comment by quillo-xi** [comment]
Just looking here since I encountered this when my son and I started getting into Deep Mob Learning but now that we're starting a fresh play-through, we want to focus on large scale automation and this popped up again.

Been open a year and this issue has no resolution or updates?

**Comment by knoxhack** [comment]
Should be fixed
