### ISSUE TITLE
Minestrappolation crusher bug

### ISSUE THREAD

**Issue by zmounce** [NFINIT-Development/AstroBlock#59]
when i used the crusher from minestrap it crashed my server and now it refuses to start all the way
my minecraft client is still working just the server crashed 
[crash-2019-04-21_14.10.48-server.txt](https://github.com/NFINIT-Development/AstroBlock/files/3101282/crash-2019-04-21_14.10.48-server.txt)

**Comment by Andr0oS** [comment]
I think the cause is having nothing in it being crushed while it still has fuel, you can use MCEdit to remove the remaining burn time if you can find the block in it, or NBTExplorer, if you can wade through all the data to find it.
