### ISSUE TITLE
Start Map

### ISSUE THREAD

**Issue by Zaptizzi** [NFINIT-Development/AstroBlock#64]
Okay so im tring to run a single player world and after clicking on create new world I get a crash so here is the log. Please note I have 8GB though the mcmulti launcher and my I7-7700k LQ/ 16GB DDR4/ Readon vega 64 LQ so my pc is beefy please help me whats going. Thanks I'll check back later.

[New Paste 1.txt](https://github.com/NFINIT-Development/AstroBlock/files/3403322/New.Paste.1.txt)

**Comment by A-UNDERSCORE-D** [comment]
```
# There is insufficient memory for the Java Runtime Environment to continue.
# Native memory allocation (malloc) failed to allocate 1039856 bytes for Chunk::new
# An error report file with more information is saved as:
```
Allocate more memory to the pack.

**Comment by A-UNDERSCORE-D** [comment]
Actually, I stand corrected. Seems something else broke causing the game to ask for a bunch of memory. What exactly? I'm not sure
