### ISSUE TITLE
Mekanism Thermal Evaporation Blocks Freeze Server

### ISSUE THREAD

**Issue by pyriell** [NFINIT-Development/AstroBlock#65]
This is a known issue with the version of Mekanism in the pack:
https://github.com/mekanism/Mekanism/issues/5417
https://github.com/mekanism/Mekanism/issues/5354

Shortly after placing any of the frame blocks for a thermal evaporation tower, the server stops doing anything useful.  You can break blocks, but they won't drop anything, you can't interact with machines, doors, etc.

Not being able to build the towers puts the Mekanism fusion reactor out of reach, but I guess it's not strictly necessary.  However, in my world I'm at the point where I need lithium for a few things.  I guess the workaround is to process a bit of a salt instead.

I haven't tried updating Mekanism yet.  I haven't had any success replacing individual mods in the past, and this pack has so many customized recipes that it would probably break progression at a minimum.

Update:  I was mistaken about salt being a workaround.  It doesn't appear there's a way to go from the brine that it can produce to lithium without using the thermal evaporation setup.  The induction providers and the like from Mekanism are all gated behind this process.

**Comment by ErraticHail2012** [comment]
You can build and use the multiblock if you place the controller before any of the frame blocks. Just make sure they aren't alone without it.

**Comment by pyriell** [comment]
Well, that's handy, thanks.  I just updated Mekanism, as doing so doesn't seem to adversely affect anything in the pack.

**Comment by m9365428** [comment]
Just unlocked the pack and updated
Mekanism-1.12.2-9.8.383
MekanismGenerators-1.12.2-9.8.1.383

Pack loads and allows Evaporator to be built in any order. Recommend pushing those 2 updates.
