### ISSUE TITLE
Ticking Entity issue causing crash on loading world (plant gatherer & cactus?)

### ISSUE THREAD

**Issue by pyriell** [NFINIT-Development/AstroBlock#66]
[crash-2019-08-03_10.26.52-server.txt](https://github.com/NFINIT-Development/AstroBlock/files/3463922/crash-2019-08-03_10.26.52-server.txt)

Currently, my AstroBlock world just dies on startup.  It gets to the point of loading terrain, then the client crashes, and I have to go manually halt the java process.

I think this is related to the cactus farm I built yesterday to help with getting into Environmental Tech and its litherite.  I have a plant gatherer from Industrial Foregoing with a range upgrade installed (I forget what level), sitting in front of about 40 cacti.  I checked the issue tracker for Industrial Foregoing, and didn't see any complaints similar to this regarding the gatherer.  So I'm guessing the problem is the way the weird little saguaros you have instead of vanilla cacti are responding to something when the world loads.  I just don't know offhand what mod those come from.

**Comment by Enderdraak** [comment]
I have a similar crash. I unfortunately can not find the crash report. But it happens when a creeper explodes on farmland (the clay version).
