### ISSUE TITLE
repeating rendering crash when joining server

### ISSUE THREAD

**Issue by falizure** [NFINIT-Development/AstroBlock#74]
After taking the red pill dying and becoming a android i almost instantly crashed while playing on a friends server, it happens immediately whenever i try and log in as well and appears to be with the one probe rendering and the android hub, at least from what i can gather.

dragging files or copy pasting does not appear to be working here for some reason so im providing a pastebin to the crash report instead 

https://pastebin.com/UZ83Evde

**Comment by ErraticHail2012** [comment]
Having same problem, did you also place the Android hub directly on the sealed tin block?

Turns out it was the android Charging Station. Top block was connected w aluminum wire and the wire was freaking out

**Comment by falizure** [comment]
nope, no hub or nothing, infact i was on the overworld, just in the middle of a ruined building with a few processing machines and storage, nothing else android related at all except the charger which i didnt even get a chance to look at once i took the pill, the crash was almost immediate.
