### ISSUE TITLE
Can't find copper and tin ore in asteriod

### ISSUE THREAD

**Issue by frost0116** [NFINIT-Development/AstroBlock#77]
I download the modpack version 1.1.31 from curseforge and put all the config/script files. However, I can't find any copper or tin ore in the asteriod, even I have found diamond in an asteriod. The compressor needs to be crafted by the copper ingot so that the game cannot go on.

**Comment by Hypario** [comment]
The compressor you want only need iron (and a bit of wood), you don't need any copper or tin ore as they can be made from iron.
Here is a capture of the craft : https://pix.watch/-PWDW-/5lMKtU.png

**Comment by frost0116** [comment]
Fixed after downloading the pack again and reinstall. Thanks.
