### ISSUE TITLE
Bug Report: AstroBlock won't launch

### ISSUE THREAD

**Issue by GCPleb** [NFINIT-Development/AstroBlock#79]
## Bug Report
Whenever I attempt to start the modpack through the launcher it keeps crashing and coming back to the launcher.

## Steps to Reproduce.
(On Mac OS)
1. Press play on the profile on Twitch
2. Press play on the launcher and wait.

## Logs
Logs : https://paste.feed-the-beast.com/view/9086e541
Crash Report: https://paste.feed-the-beast.com/view/658a8167
Crash Report: https://paste.feed-the-beast.com/view/92c3c7b2
# Client Information
Twitch Launcher 

* Modpack Version:1.1.31
* Server/LAN/Single Player: Singleplayer
* Optifine Installed: No
* Shaders Enabled: no
* Amount of Ram Allocated: 4600mb

**Comment by Firephoenix363** [comment]
Hey did you solved your problem and if yes could you explain to me how cause I have the same problem. 
Thanx's for answering

**Comment by Firephoenix363** [comment]
@GCPleb
