### ISSUE TITLE
Game crash

### ISSUE THREAD

**Issue by spirl1337** [NFINIT-Development/AstroBlock#93]
I had multiple crashes when I was looking on Charging station from MatterOverdrive.
[crash-2019-11-16_19.32.04-client.txt](https://github.com/NFINIT-Development/AstroBlock/files/3854308/crash-2019-11-16_19.32.04-client.txt)
[crash-2019-11-16_19.47.10-client.txt](https://github.com/NFINIT-Development/AstroBlock/files/3854309/crash-2019-11-16_19.47.10-client.txt)
[crash-2019-11-16_18.46.11-client.txt](https://github.com/NFINIT-Development/AstroBlock/files/3854310/crash-2019-11-16_18.46.11-client.txt)

**Comment by ROMVoid95** [comment]
i can say right now thats a HUGE known issue with the Charging Station, happened many times on my servers, the only fix i know that works and can be easily done without loading into the chunk its in is to delete the block in the region file
